<a href="https://colab.research.google.com/github/mukthipriya/aiml-intership/blob/main/task_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Normalize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

# Try different values of K
for k in range(1, 11):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    print(f"K={k}, Accuracy={accuracy_score(y_test, y_pred):.2f}")
    print(confusion_matrix(y_test, y_pred))
import numpy as np

# Select two features
X_reduced = X_scaled[:, 2:4]  # petal length & width
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X_reduced, y, test_size=0.3, random_state=42)

# Fit KNN on reduced features
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_r, y_train_r)

# Meshgrid for decision boundary
h = 0.02
x_min, x_max = X_reduced[:, 0].min() - 1, X_reduced[:, 0].max() + 1
y_min, y_max = X_reduced[:, 1].min() - 1, X_reduced[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                     np.arange(y_min, y_max, h))
Z = knn.predict(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)

plt.figure(figsize=(10, 6))
plt.contourf(xx, yy, Z, alpha=0.4)
plt.scatter(X_reduced[:, 0], X_reduced[:, 1], c=y, edgecolor='k', s=20)
plt.title("KNN Decision Boundary (Petal Length vs Width)")
plt.xlabel("Petal Length (normalized)")
plt.ylabel("Petal Width (normalized)")
plt.show()

output:
K=1, Accuracy=1.00
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
K=2, Accuracy=1.00
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
K=3, Accuracy=1.00
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
...
K=10, Accuracy=0.98
[[19  0  0]
 [ 0 13  0]
 [ 0  1 12]]